name: Audit
on:
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
    branches:
      - '**'
    tags-ignore:
      - v*

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Audit
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
